import { readFileSync } from "node:fs";
import { createClient, createAccount } from "genlayer-js";
import { testnetBradbury } from "genlayer-js/chains";
import { TransactionStatus } from "genlayer-js/types";
const account = createAccount(process.env.PRIVATE_KEY);
const client = createClient({ chain: testnetBradbury, account });
const CONTRACT = readFileSync("contract.txt", "utf8").trim();
const KEY = "btc_usd";
const QUESTION = "What is the current spot price of one Bitcoin (BTC) in US dollars (USD)? Return only the numeric USD amount.";
const SOURCES = ["https://api.coinbase.com/v2/prices/BTC-USD/spot", "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd", "https://api.kraken.com/0/public/Ticker?pair=XBTUSD"];
const TOLERANCE_BPS = 200;
const MAX_SPREAD_BPS = 500;
const DECIMALS = 2;
console.log("Registering feed", KEY, "on", CONTRACT);
const txHash = await client.writeContract({ address: CONTRACT, functionName: "register_feed", args: [KEY, QUESTION, JSON.stringify(SOURCES), TOLERANCE_BPS, MAX_SPREAD_BPS, DECIMALS] });
console.log("register tx:", txHash);
await client.waitForTransactionReceipt({ hash: txHash, status: TransactionStatus.ACCEPTED, retries: 300 });
const tx = await client.getTransaction({ hash: txHash });
console.log("txExecutionResultName:", tx?.txExecutionResultName);
const ok = (tx?.txExecutionResultName === "FINISHED" || tx?.txExecutionResultName === "FINISHED_WITH_RETURN");
console.log(ok ? ">>> REGISTER OK" : ("!!! not clean -> " + tx?.txExecutionResultName));
